[rocksdb]
# wal-recovery-mode = 2
# wal-dir = ""
# wal-ttl-seconds = 0
# wal-size-limit = 0
# max-total-wal-size = "4GB"
# max-background-compactions = 6
# max-background-flushes = 2
# base-background-compactions = 1
# max-manifest-file-size = "20MB"
# create-if-missing = true
# max-open-files = 40960
# enable-statistics = true
# stats-dump-period-sec = 600
# compaction-readahead-size = 0
# info-log-max-size = 0
# info-log-roll-time = "0s"
# info-log-dir = ""
# rate-bytes-per-sec = 0
# max-sub-compactions = 1
# writable-file-max-buffer-size = "1MB"
# use-direct-io-for-flush-and-compaction = false
 
[rocksdb.cf]
# block-size = "64KB"
# block-cache-size = "256MB"
# cache-index-and-filter-blocks = true
# bloom-filter-bits-per-key = 10
# block-based-bloom-filter = false
# compression-per-level = "no:no:lz4:lz4:lz4:zstd:zstd"
# write-buffer-size = "128MB"
# max-write-buffer-number = 5
# min-write-buffer-number-to-merge = 1
# max-bytes-for-level-base = "512MB"
# target-file-size-base = "32MB"
# level0-file-num-compaction-trigger = 4
# level0-slowdown-writes-trigger = 20
# level0-stop-writes-trigger = 36

