[rocksdb]

[rocksdb.cf]
compression-per-level = "no:no:lz4:lz4:lz4:zstd:zstd"
block-size = "64KB"
write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "512MB"
target-file-size-base = "32MB"

level0-file-num-compaction-trigger = 4
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
cache-index-and-filter-blocks = true

# should tune to 256MB~2GB.
block-cache-size = "256MB"
